### ISSUE TITLE
Cannot read property 'normalize' of undefined

### ISSUE THREAD

**Issue by jmcandia** [VitorLuizC/normalize-text#13]
Hi,

I am currently working on a project developed with the NestJS framework and TypeScript, and when I try to use the normalizeText() function I get the error `TypeError: Cannot read property 'normalize' of undefined`.

The full error message is as follows:
```
TypeError: Cannot read property 'normalize' of undefined
    at normalizeDiacritics (C:\Users\jmcandia\Repositorios\proyecto-morpheus\morpheuscrm-api\node_modules\normalize-text\src\normalizeDiacritics.js:12:16)
    at C:\Users\jmcandia\Repositorios\proyecto-morpheus\morpheuscrm-api\node_modules\@bitty\pipe\src\pipe.js:23:53
    at Array.reduce (<anonymous>)
    at Object.<anonymous> (C:\Users\jmcandia\Repositorios\proyecto-morpheus\morpheuscrm-api\node_modules\@bitty\pipe\src\pipe.js:23:20)
    at new User (C:\Users\jmcandia\Repositorios\proyecto-morpheus\morpheuscrm-api\src\users\users.entity.ts:82:44)
    at EntityMetadata.Object.<anonymous>.EntityMetadata.create (C:\Users\jmcandia\Repositorios\proyecto-morpheus\morpheuscrm-api\src\metadata\EntityMetadata.ts:527:23)
    at EntityMetadataValidator.Object.<anonymous>.EntityMetadataValidator.validate (C:\Users\jmcandia\Repositorios\proyecto-morpheus\morpheuscrm-api\src\metadata-builder\EntityMetadataValidator.ts:118:47)
    at C:\Users\jmcandia\Repositorios\proyecto-morpheus\morpheuscrm-api\src\metadata-builder\EntityMetadataValidator.ts:46:56
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.Object.<anonymous>.EntityMetadataValidator.validateMany (C:\Users\jmcandia\Repositorios\proyecto-morpheus\morpheuscrm-api\src\metadata-builder\EntityMetadataValidator.ts:46:25)
```

The version of `normalize-text` I am using is 2.3.2

**Comment by VitorLuizC** [comment]
You probably passed `undefined` as argument to `normalizeText`. Can you show a piece of code that causes this bug?

**Comment by jmcandia** [comment]
You were right, the error was in the class itself because the constructor was not passing the corresponding value.
